### ISSUE TITLE
RestEasy chin rest assembly difficulties

### ISSUE THREAD

**Issue by marqu310** [MonkeyGone2Heaven/SCNI_Toolbar#5]
We have printed the RestEasy chin rest parts and purchased the recommended components, but are having difficulty assembling everything together using the included CAD screenshots alone. We would appreciate further guidance, particularly on the following issues:

- The [leveling feet](https://www.mcmaster.com/23015t66) do not fit within the printed table clamp mount because of length. However, it appears that if the screw were any shorter to accommodate the clamp (e.g., shortening the feet with a saw), it would not be long enough for the [plastic five arm knob](https://www.mcmaster.com/59625k76) while still effectively making contact with the table.
- It is unclear how to connect the printed table clamp with the T-slot rod. The rod is not threaded upon arrival from the manufacturer and is too small for the [button head hex drive screw](https://www.mcmaster.com/91255a545).
- It is unclear how best to use connect the printed chin rest crossbars with the T-slot rod. It may be that the [plastic three arm knob](https://www.mcmaster.com/57715k44) connects with the [1/4 -20 slide-in T-nut](https://8020.net/3382.html), which is then inserted into the T-slot. However, we are uncertain about what to do with the remainder of the parts, including the [linear bearing pads](https://8020.net/6491.html), [black-oxide sleeve washers](https://www.mcmaster.com/93762a100), [cap nuts](https://www.mcmaster.com/91855a550), etc.
- The printed chin rest is not threaded nor does it include a hole for the four-arm comfort grip knob. What are the recommended steps to connect the four-arm knob to the chin rest?

![image1](https://user-images.githubusercontent.com/55113226/64575103-c8616980-d337-11e9-8ced-cb9b8edd2f1d.jpeg)
![image2](https://user-images.githubusercontent.com/55113226/64575104-c8616980-d337-11e9-9988-7dd410ba94f6.jpeg)
![image3](https://user-images.githubusercontent.com/55113226/64575105-c8616980-d337-11e9-8e03-0b77f40b2dcb.jpeg)
![image4](https://user-images.githubusercontent.com/55113226/64575106-c8616980-d337-11e9-8fd8-49b23987acdf.jpeg)
![image5](https://user-images.githubusercontent.com/55113226/64575108-c8616980-d337-11e9-84ca-edce509a27d5.jpeg)
![image6](https://user-images.githubusercontent.com/55113226/64575109-c8616980-d337-11e9-8d29-a6c125833f1f.jpeg)

**Comment by Phenomenal-Cat** [comment]
Sorry we haven't provided more info on assembling the RestEasy parts. I must also admit that I haven't actually printed (or assembled) this latest version of the design yet, so it may be that there are some errors, for which I apologise. 

- The leveling feet issue is an oversight on my part having reduced the opening width of the clamps in the current design. The easiest solution would be to return those leveling feet to McMaster and instead purchase separate feet (https://www.mcmaster.com/6103k172) and threaded rods of suitable length (https://www.mcmaster.com/98750a068).

- Where did you order your T-slot profile from? Most companies selling extruded aluminium profile will offer the option of drilling and/or tapping the end holes for you. For the Imperial measurement version (i.e. 1x1" profile), these should be 1/4"-20 threads at least 1" deep to accommodate the button head screw. If you don't have access to a machine shop, you could tap the holes by hand yourself using one of these: https://www.mcmaster.com/27175a218 (plus a tap wrench like this: https://www.mcmaster.com/2546a23), since aluminum is relatively soft. Just turn the tap a few turns at a time and clean the debris out as you go.

- The chin rest crossbar should indeed slot into the t-slot as you have it in the 4th photo. Depending on the 3D printing process used the protrusion on the medial side of the slot may need to be filed down slightly to fit nicely. The linear bearing pads were originally intended as an alternative to that protrusion, to keep the crossbar lined up vertically in the t-slot, but is not necessary for this design. 

- The chin rest cup should have a hole on the underside to accommodate the 1/4"-20 screw of the four-armed knob, as well as a slot on the side facing the subject to accommodate a 1/4"-20 nut (as shown in the attached). Having checked the files on Thingiverse, I see that the current .stl does not (although the FreeCAD file did). I've updated the chin rest cup .stl just now to the version that includes these features. However, since you already have this part printed, I'd recommend simply drilling and tapping a hole in the bottom of the chin rest: use a 13/64" (#7) drill bit for the hole, being careful not to go all the way through. Then use the same 1/4"-20 tap that you used for tapping the holes in the aluminum t-slot (https://www.mcmaster.com/27175a218). 

<img width="715" alt="Screen Shot 2019-09-09 at 11 43 04 PM" src="https://user-images.githubusercontent.com/7523776/64583083-beeaf800-d35d-11e9-91df-d4087ad44b0b.png">

Again, sorry for these errors and lack of info on my part, and thank you for providing such helpful information (for me and others). You should be able to return any parts you don't need to McMaster for a refund (the sleeve washers and cap nuts were also part of the previous design and are no longer necessary), and I will update the web page to reflect these amendments. At some point I will try to add a more detailed description of the assembly process. In fact, it would be incredibly helpful if I could use some of your attached photographs for illustration purposes, if that's ok? Please let me know how you get on and if you encounter any further issues in assembly.

**Comment by marqu310** [comment]
Thank you for your responsiveness to this. We are going to send back the parts we don't need, drill the T-slot rods with the parts you recommended, get the new leveling feet, and reprint the chin cup. You are welcome to use any of the pictures. We will post more to this thread once we get the set-up completed. Best wishes.
